//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCartera.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class seguridadusuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public seguridadusuario()
        {
            this.tmonedas = new HashSet<tmoneda>();
            this.tmovimientoes = new HashSet<tmovimiento>();
            this.tcategorias = new HashSet<tcategoria>();
            this.tcuentas = new HashSet<tcuenta>();
        }
    
        public int Id { get; set; }
        public int IdRol { get; set; }
        public string Email { get; set; }
        public string NomUsuario { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public bool Activo { get; set; }
        public string Clave { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmoneda> tmonedas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmovimiento> tmovimientoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tcategoria> tcategorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tcuenta> tcuentas { get; set; }
        public virtual seguridadrol seguridadrol { get; set; }
    }
}
