//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCartera.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmoneda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tmoneda()
        {
            this.tcuentas = new HashSet<tcuenta>();
            this.tsaldoxcategorias = new HashSet<tsaldoxcategoria>();
        }
    
        public int Id { get; set; }
        public int Id_Usuario { get; set; }
        public string Descripcion { get; set; }
        public string Simbolo { get; set; }
        public bool Activo { get; set; }
    
        public virtual seguridadusuario seguridadusuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tcuenta> tcuentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tsaldoxcategoria> tsaldoxcategorias { get; set; }
    }
}
