//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCartera.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmovimiento
    {
        public int Id { get; set; }
        public int Id_Cuenta { get; set; }
        public int Id_Categoria { get; set; }
        public int Id_Usuario { get; set; }
        public int Tipo { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Monto { get; set; }
    
        public virtual seguridadusuario seguridadusuario { get; set; }
        public virtual tcategoria tcategoria { get; set; }
        public virtual tcuenta tcuenta { get; set; }
    }
}
