//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCartera.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tversion
    {
        public int IdVersion { get; set; }
        public Nullable<int> VerBD { get; set; }
        public string Script { get; set; }
        public string Detalles { get; set; }
    }
}
